### ISSUE TITLE
Clean up README.md

### ISSUE THREAD

**Issue by seananderson** [cgrandin/csas-style#10]
The README.md file should probably include basic instructions for a user to get started. We should probably move at least some of the current details into a separate file or into the repo's wiki.

Soon we may want to also link to the csasdown repo as an alternative front end to using csas-style. Note that csasdown has some helper functions for installing arial on Windows with `add_arial()`. Longterm I'd like to get Arial working with tinytex to avoid the MikTeX headaches.

**Comment by cgrandin** [comment]
We could also create a git tag and just erase and start a new README.md at the next commit so that the old information is still easily retrievable if needed in the future.

**Comment by cgrandin** [comment]
Closing to archive.
