### ISSUE TITLE
Travis CI testing

### ISSUE THREAD

**Issue by seananderson** [cgrandin/csas-style#11]
After an exceedingly painful day last week of pushing, tweaking the config script to add one more LaTeX package, and trying again, we now have continuous integration testing for csas-style:
https://travis-ci.org/pbs-assess/csas-style

Also see the front-page/README.md for the badge https://github.com/pbs-assess/csas-style

This will ensure that we don't break the example but we can also use this set up to automatically compile any documents that use csas-style on Travis. If you break it you get a nasty e-mail. :)

@ricardd thanks for the pain of trying a broken example, which made this finally happen.

**Comment by cgrandin** [comment]
Closing to archive.
