### ISSUE TITLE
Check out latex package accsupp for Web Accessibility.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/csas-style#3]
Someone should look into this when time. If we can get it working then we should have a submittable Res Doc that won't need any more tweaking by anyone to make it publishable.

**Comment by andrew-edwards** [comment]
Though a quicker first try (as I think it's just the alternate text for figures that we have to worry about) is:

One of the requirements for web accessibility is 'alternate text' for .pdf readers.

Could try looking at the last comment of

http://tex.stackexchange.com/questions/75102/need-alt-text-for-images-in-pdf-for-screen-readers

which says:

" You can use PDF tooltips with the pdfcomment package. Then the 'alt' text (aka tooltip) is read!

\documentclass{article}
\usepackage{graphicx}
\usepackage{pdfcomment}
\pagestyle{empty}

\begin{document}
one two three

\pdftooltip{\includegraphics{img.png}}{This is the ALT text}%

four five six
\end{document}
"

I hadn't tried before as didn't think it would work with dvips, but am now using pdflatex anyway (since .ps files weren't being ignored properly by the screen readers).

**Comment by andrew-edwards** [comment]
The \pdftooltip command seems to work!!! Yes. More tomorrow ...

**Comment by andrew-edwards** [comment]
\pdftooltip seems to work for my two POP appendices. Won't pre-emptively close this Issue until the document gets published.

**Comment by cgrandin** [comment]
Closing to archive.
