### ISSUE TITLE
Ordering of multi-author papers in bibliography

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/csas-style#4]
This is the one CSAS (maybe from CJFAS) rule that I couldn't quite automate. Here are some earlier notes; I think it is only (iii) that doesn't quite work correctly.

The ordering of papers for 2 and >2 authors is fiddly and maybe not possible to automate, and so just do manually prior to submission
(edit the order of the .bst file). The CJFAS rules are:

References must be listed in alphabetical order according to the name of the first author and not numbered. References with the same first author are listed in the following order. 

(i) Papers with one author only are listed first in chronological order, beginning with the earliest paper. 

(ii) Papers with dual authorship follow and are listed in alphabetical order by the last name of the second author. 

(iii) Papers with three or more authors appear after the dual-authored  papers and are arranged chronologically.  **These currently get arranged alphabetically (by second, or higher if necessary, author, instead of by year)**.

For Redbanded I had to manually (in the .bbl file, so don't re-bibtex):

 - re-order Edwards et al. (2012 and 2014 order)
 - re-order Yamanaka et al. references into chronological order.

**Comment by seananderson** [comment]
The options as implemented through the custom-bib package are listed starting on page 10 half way down here:
http://ctan.forsale.plus/macros/latex/contrib/custom-bib/merlin.pdf

I'd need to experiment to figure out if one of them follows the necessary style. Maybe `seq-yr`?

I know that in cases where the authors are the same, BibTeX orders by the title alphabetically. But you probably want them to appear in order of appearance in the text (e.g. Smith 1999a then Smith 1999b). And you can cheat to get around that with something like:

```
Title = {\setbox0=\hbox{1}{Global} database on... },
and
Title = {\setbox0=\hbox{2}{Description} of Fisheries... },
```

**Comment by seananderson** [comment]
By some miracle I found the original custom-bib template file from 2008 when I first made cjfas.bst. I just uploaded it here: https://github.com/seananderson/bst/blob/master/cjfas.dbj

It may be as simple as uncommenting the line with `seq-yr` and re-running it depending what other changes you've made to the .bst.

**Comment by andrew-edwards** [comment]
I'll make a simple example that we can play with.

**Comment by andrew-edwards** [comment]
I created an example - has lots of multi-author papers with same name. In bit-testing branch (which was meant to say bib-testing, but I didn't spot the typo until later).

**Comment by seananderson** [comment]
I think [this](https://github.com/seananderson/csas-style/commit/21e235fd7abb64c5856a53dc8b338c626620a18c) commit should fix it. Not sure what the main `.bst` file is to update.

**Comment by andrew-edwards** [comment]
Awesome thanks - yes it works. The .bst file you edited is the one.

**Comment by andrew-edwards** [comment]
Damn - I found an example in our POP assessment that shows that two-author papers don't always come first. They happened to be correct in my example because the surnames of the second authors started with B. Have added an example (Edwards and Zzzz) to the test example. Commit d44c0e1

**Comment by andrew-edwards** [comment]
The order of POP will probably get fixed once I tidy up the .bib file - the .bib file is an inconsistent mess with some full first names and some initialised first names.

**Comment by seananderson** [comment]
After playing around with it I think this is just a weird bug if the 2nd author's last name happens to be Zzzzz. Probably because there's an if else statement in the .bst file of `{ "zzzzz" 't := }`.

If on the other hand you co-authored with Julian Zebra, it looks fine to me. 

![screenshot](https://user-images.githubusercontent.com/19349/30981314-d6e7cbf0-a438-11e7-95ec-76c39e2b2414.png)

```
@article{ez90,
   author    = {A. M. Edwards and J. Zebra},
   title     = {Zooplankton mortality and the dynamical behaviour of plankton population models},
   fulljournal   = {Bulletin of Mathematical Biology},
   journal   = {Bull.~Math.~Biol.},
   year      = {1999},
   volume    = {61},
   pages     = {303-339}
}
```

**Comment by andrew-edwards** [comment]
Thanks. Sorry about the extra work. For POP it is because the .bib file is a mess and I'll have to redo it.

**Comment by andrew-edwards** [comment]
For the record, I fixed Jean-Baptiste's POP .bib file and the ordering works perfectly (he had an inconsistent mixture of initials with and without periods, plus some first names). So all good!
