### ISSUE TITLE
The .bst file seems to strip out hyphens from first names

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/csas-style#5]
For Redbanded Rockfish assessment, the .bbl file incorrectly strips out hyphens in hyphenated first names. Fixing manually for Redbanded in for Lecomte (2013), both J.-B. and M.-P. Maybe just a quirk of my .bib file, but other .bst files don't seem to mess this up.

I can maybe provide a minimal working example one day. Not a huge issue but I'll note in the readme file.

**Comment by cgrandin** [comment]
Closing to archive.
