### ISSUE TITLE
Should Matt's frontmatter branch be merged into master?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/csas-style#9]
Was on a conference call yesterday and Dan Ricard in Gulf Region mentioned that he was using our csas-style stuff. I think he may have just got an older version of mine, so I was going to let him know that you guys have been extending it. But with the two branches I was just wondering if they should be merged.

And (Sean) if Dan is not a member of pbs-assess then he should still fork it, yes? And if he makes improvements then we would pull them into our master (he can do a pull request). In other words, we don't want to start making outside people members of pbs-assess.

**Comment by seananderson** [comment]
Just noticed that this issue. I wasn't getting notification previously on this repo unless you added my username with `@` before it. I'm "watching" it now so I should get notifications.

The `frontmatter` branch was merged into master a while ago now.

It's no problem adding @ricardd to pbs-assess if he wants, but yes, the generic answer for anyone not a member to make a contribution would be to fork it and make a pull request. We can probably also give permission on a repository-by-repository basis.
